### ISSUE TITLE
Social promo for WPDiversity events in India 2021/09

### ISSUE THREAD

**Issue by abhansnuk** [wpmarketingteam/Marcomms-Rolling-tasks#37]
_Summary from Slack_
 **Task:** request for global social media promotion
 
 **Background:** Query raised by Nalini at WPDiversity meeting 2021/9/15 if these events were to be included on the social media promotion. Jill confirmed - note tight turnaround. 

**Key information:** Note from Jill 2021/9/17: use Eventbrite links directly for remaining events on 18 and 24.
The Sept 18 ticket sales end 10 min before the event (6:50pm IST).
The Sept 24 ticket sales end 30 min before the event (8:30am IST).

Eventbrite links can be found on Make https://make.wordpress.org/community/2021/09/15/wpdiversity-events-in-september-attention-india/

For Sept 24 event, Jill advises there will be a flyer and promo video available which will be made available. Asked if length of video to understand how and where it can be included. Suggested it can be linked from the GitHub.

**Working document for Q3 social updates for WPDiversity** https://docs.google.com/document/d/11yAywSvulW9eGKrq1_v6biLdsvea_yr87nRo7yRHqOM/edit?usp=sharing

**Reference links:** Link to  Marketing Slack discussion for reference: https://wordpress.slack.com/archives/C0GKJ7TFA/p1631912100312700

**Comment by murillol** [comment]
_Linkedin_
Date: Monday 20 September 2021
**Account**: Make WordPress Marketing Team

If you want more women to speak at your #WordPress meetups or WordCamps in India, then you can't miss the upcoming #WPDiversity event "Empower Women Speakers For Your WordPress Events in India"!

The workshop has 2 parts, on Friday 24 September and Saturday 25 September 2021. Both sessions are from 3.30am to 5.30am UTC (9am - 11am IST). 

You will learn how to run the workshop that has been proven to increase the number of Women speakers in WordPress Communities all over the world. You will learn some of the reasons why women aren’t submitting talks, help them overcome their personal barriers to public speaking, and much more.

Register now: https://www.eventbrite.com/e/empower-women-speakers-for-your-wordpress-events-in-india-sept-24sept-25-registration-151088233975

Please help us spread the word! Share this post!


_Twitter_
**Date**: Wednesday 22 September 2021
**Account**: @wordpressevents 

If you want more women to speak at your #WordPress events in India, register for this #WPDiversity training! You will learn how to run the workshop proven to increase the number of Women speakers in WordPress Communities globally. 

📆 24 & 25 Sept. 2021
https://www.eventbrite.com/e/empower-women-speakers-for-your-wordpress-events-in-india-sept-24sept-25-registration-151088233975

**Comment by murillol** [comment]
**Update**: Jill shared the [video](https://wordpress.slack.com/archives/C0GKJ7TFA/p1632162297315700?thread_ts=1631912100.312700&cid=C0GKJ7TFA) and [flyer ](https://wordpress.slack.com/files/U02S5FUKN/F02F7PD6MPW/empower_women_speakers_india_2021.pdf)on 20 September, I added subtitles and edited out a pause or two, and here is the [final version](https://drive.google.com/file/d/1eqwg6eOSg7peUYLW10IynHUCssVadNEE/view?usp=sharing).  @abhansnuk pls let me know if we can use it

**Comment by abhansnuk** [comment]
Thanks @murillol . Where is the video being hosted to be able to link it?

**Comment by murillol** [comment]
> Thanks @murillol . Where is the video being hosted to be able to link it?

Jill sent this link: https://cloudup.com/coGSY1ytGYT and the one I edited is just in a Google Drive

**Comment by nalininsbs** [comment]
@murillol could you please add the link to the edited and subtitled video on WP Marketing for future use please, and any other links of posts. This can then be closed. Abha confirmed it should move it to done on the rolling tasks board and the mapping tasks aggregate board. Thank you.

**Comment by murillol** [comment]
> @murillol could you please add the link to the edited and subtitled video on WP Marketing for future use please, and any other links of posts. This can then be closed. Abha confirmed it should move it to done on the rolling tasks board and the mapping tasks aggregate board. Thank you.

Hi Nalini, the link to the video is included in my [21 September comment ](https://github.com/wpmarketingteam/Marcomms-Rolling-tasks/issues/37#issuecomment-924424008).
