### ISSUE TITLE
Promote call for questions on FSE by 2021/10/27

### ISSUE THREAD

**Issue by abhansnuk** [wpmarketingteam/Marcomms-Rolling-tasks#51]
Request to Marketing from @ annezazu on Slack for help  promoting this call for questions or concerns on Full Site Editing in relation to release version 5.9. Deadline for submissions 27 October 2021.

Main push before the go/no go date this week. 

https://make.wordpress.org/core/2021/10/13/submit-full-site-editing-questions-by-oct-27th/

**Comment by nalininsbs** [comment]
Props to: @megphillips91 , @meherbala , Herb Miller, @abhansnuk , @nalininsbs , @OlaIola , @vimes1984 , Mary Baum, Mark Smallman for contributing to this.
