### ISSUE TITLE
WPDiversity event promo 27 August 2021

### ISSUE THREAD

**Issue by murillol** [wpmarketingteam/Marcomms-Rolling-tasks#7]
[Location of working document](https://docs.google.com/document/d/11yAywSvulW9eGKrq1_v6biLdsvea_yr87nRo7yRHqOM/edit)

**Comment by abhansnuk** [comment]
Information from Jill Binder:
Our second workshop of August 2021, our diverse speakers workshop, is ready for creating social media posts when you see fit.
You can promote either:
https://make.wordpress.org/community/2021/08/12/upcoming-workshop-how-to-own-your-expertise-start-speaking-at-wordpress-events/
https://www.eventbrite.com/e/how-to-own-your-expertise-start-speaking-at-wordpress-events-ameremea-tickets-166129633205
Event day/time: Friday, August 27th, 2021 @ 5-6:30pm UTC
Free to attend
Tickets are available until 10 minutes before @ 4:50pm UTC
This workshop is for:
* People from underrepresented groups in WordPress, in terms of gender, race, class, sexuality, ability, age, etc.
* Participants in our Allyship program who have taken the “Allyship for WordPress event organizers” workshop.
